- docker: "alloy"
  github: "alloy"
  deploy:
    branch: "pulsar"
    # release: "v1.11.2-57673b6"

- docker: "kayron"
  github: "kayron"
  deploy:
    release: "v0.5.3"

- docker: "pulsar"
  github: "pulsar"
  deploy:
    release: "v0.1.0"

- docker: "specta"
  github: "specta"
  deploy:
    branch: "pulsar"
    # release: "v0.2.5"

- docker: "splits-lite"
  github: "splits-lite"
  deploy:
    release: "v0.1.1"
    preview: true
