- docker: "alloy"
  github: "alloy"
  deploy:
    release: "v1.11.3-9fba925"

- docker: "kayron"
  github: "kayron"
  deploy:
    release: "v0.5.3"

- docker: "pulsar"
  github: "pulsar"
  deploy:
    release: "v0.1.0"

- docker: "specta"
  github: "specta"
  deploy:
    release: "v0.2.6"

- docker: "splits-lite"
  github: "splits-lite"
  deploy:
    release: "v0.1.1"
    preview: true
